$(document).ready(function()
	{
		$("#img1").on("mouseenter",function()
		{
			$(this).css("background-image","url(./images/image1.jpg)");
			$(this).css("background-size","100%");
		});
		$("#img1").on("mouseleave",function()
		{
			$(this).css("background-image","none");
		});
		$("#img2").on("mouseenter",function()
		{
			$(this).css("background-image","url(./images/image2.jpg)");
			$(this).css("background-size","100%");
		});
		$("#img2").on("mouseleave",function()
		{
			$(this).css("background-image","none");
		})
		$("#img4").on("mouseenter",function()
		{
			$(this).css("background-image","url(./images/image4.jpg)");
			$(this).css("background-size","100%");
		});
		$("#img4").on("mouseleave",function()
		{
			$(this).css("background-image","none");
		});
		$("#img5").on("mouseenter",function()
		{
			$(this).css("background-image","url(./images/image5.jpg)");
			$(this).css("background-size","100%");
		});
		$("#img5").on("mouseleave",function()
		{
			$(this).css("background-image","none");
		});
		
	});